### ISSUE TITLE
Add common uses

### ISSUE THREAD

**Issue by jessepisel** [learn-co-curriculum/fis-canvas-sync#1]
Need to add common uses so that there are example use cases for all the most common use cases. [Similar to what we have for the gem](https://github.com/learn-co-curriculum/github-to-canvas#common-uses) would be perfect. It is nice to just copy and modify as needed.

**Comment by bpurdy-ds** [comment]
Since Jeffrey is gone, I'm going to close this issue. Will look at it again if need be.
