### ISSUE TITLE
Remove CodeClan options

### ISSUE THREAD

**Issue by jessepisel** [learn-co-curriculum/fis-canvas-sync#2]
Need to remove CodeClan options from the script. At the same time can we also give more concrete examples for the canvas api and token naming scheme e.g. "ENTERPRISE_CANVAS_API_KEY" and "MORINGA_CANVAS_API_KEY"

**Comment by bpurdy-ds** [comment]
Since Jeffrey is gone, I'm going to close this issue. Will look at it again if need be.
